version: "3"
services:
  app:
    container_name: app
    build: .
    environment:
      - SECRET_WORD=${SECRET_WORD}
    command: nodemon ./app/server.js
    depends_on:
      - mongo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/usr/src/
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

# sudo docker-compose build
# sudo docker-compose up -d
